all: login.out employee.out addcustomer.out


login.out: login.c
	gcc login.c -o login.out
employee.out: employee.c
	gcc employee.c -o employee.out
addcustomer.out: addcustomer.c
	gcc addcustomer.c -o addcustomer.out
