name: Backlog Reminder
description: Reminder of the next step in the mini project.
title: "[Next Step Reminder]: "
labels: ["backlog"]
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        **This is a reminder of the next step in your mini project.**

  - type: input
    id: task_summary
    attributes:
      label: "Next Step"
      description: "Briefly describe the next step you need to work on in your project."
      placeholder: "What is the next step you need to focus on?"

  - type: textarea
    id: task_details
    attributes:
      label: "Details"
      description: "Provide any additional context or instructions that will help you remember the task."
      placeholder: "Include resources, links, or notes to remind yourself how to proceed."

  - type: input
    id: deadline
    attributes:
      label: "Deadline"
      description: "If applicable, set a date or time frame for completing this task."
      placeholder: "When do you plan to complete this?"

  - type: input
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this step for the project?"
      placeholder: "High/Medium/Low"
