name: Bug Report

description: |
  **Contact us for help!**  
  If you encounter any issues, please use this template to report bugs. The more detail you provide, the faster we can address the issue.

labels:
  - bug

assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the bug in detail**  
        This will help us identify and fix the problem quickly.
        - What did you expect to happen?
        - What actually happened?
        - When did you first notice this issue?

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: |
        Please provide details of your environment (OS, browser, version, etc.)
        Example: Windows 10, Chrome 91, Node.js 16

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: |
        Please provide a detailed description of the bug.
        What were you trying to do? What steps did you follow?
        Be as descriptive as possible, including any error messages.
      placeholder: |
        Describe the bug that occurred.
        Example: "Clicking the submit button on the form causes the app to crash."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: |
        Please list the steps to reproduce the issue.
        - Example: "1. Open the app."
        - Example: "2. Click on 'Submit'."
      placeholder: |
        1. Step 1: ...
        2. Step 2: ...

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: |
        What did you expect to happen instead of the bug occurring?
      placeholder: |
        Example: "I expected the form to submit without any errors."

  - type: input
    id: screenshot_url
    attributes:
      label: "Screenshots or GIFs (optional)"
      description: |
        If applicable, please provide a link to any screenshots or GIFs that demonstrate the bug.  
        You can upload your images to an image hosting service (like [Imgur](https://imgur.com/)) and share the link.
      placeholder: |
        Example: "https://imgur.com/abc123"

  - type: input
    id: error_log
    attributes:
      label: "Error Log (if available)"
      description: |
        If you encountered an error message or a log file, please paste it here.
        Example: "Uncaught TypeError: Cannot read property 'x' of undefined"

  - type: input
    id: version
    attributes:
      label: "Version"
      description: |
        Please include the version of the app or tool where you encountered the issue.
      placeholder: |
        Example: "v1.0.0"
