all: login.out admin.out addAdmin.out addEmployee.out addManager.out

login.out: login.c
	gcc login.c -o login.out

admin.out: admin.c
	gcc admin.c -o admin.out

addAdmin.out: addAdmin.c
	gcc addAdmin.c -o addAdmin.out

addEmployee.out: addEmployee.c
	gcc addEmployee.c -o addEmployee.out

addManager.out: addManager.c
	gcc addManager.c -o addManager.out
