name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code using actions/checkout@v3
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      # Step 3: Run Doxygen to generate documentation
      - name: Run Doxygen to generate documentation
        run: doxygen Doxyfile

      # Step 4: Upload documentation as an artifact
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v2
        with:
          name: doxygen-docs
          path: docs/html/
