name: Auto Label Issues and PRs

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels based on content
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            bug, feature, enhancement
