name: Memory Leak Check

on: [push, pull_request]

jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install valgrind
      run: sudo apt-get update && sudo apt-get install -y valgrind

    - name: Build project
      run: make

    - name: Run memory check with valgrind
      run: valgrind --leak-check=full ./your_binary
